### ISSUE TITLE
HTTP/2 403 with Discogs scraper

### ISSUE THREAD

**Issue by houdini69** [koillection/koillection#1013]
It looks like there have been some changes on Discogs again.

I got a 403 error when trying the Discogs scraper provided in the wiki. For example:

`HTTP/2 403 returned for "https://www.discogs.com/fr/artist/162564-Astor-Piazzolla".`

xPath syntax is overwhelming for me. Is the blockage related to Discogs?

**Comment by benjaminjonard** [comment]
Apparently Discogs put up some protections against scraping. I'm already searching for solutions, but for now I don't know if I'll be able to find a reliable way to do this

**Comment by benjaminjonard** [comment]
As a temporary solution, you can download the HTML page you want to scrap and upload it to Koillection (click on "Scrap HTML file")

**Comment by houdini69** [comment]
Unfortunately, scraping saved HMTL page doesn't seem to work. I got nothing when clicking Scrap button.

**Comment by houdini69** [comment]
Sorry. I finally succeeded with saved HTML page.

**Comment by frank20a** [comment]
Run into the same issue with Discogs. Use http://... instead of https and it works
