### ISSUE TITLE
Show item name in the "related items" list

### ISSUE THREAD

**Issue by ekamil** [koillection/koillection#1018]
Currently it's only an image, which isn't useful when you have a few items that look the same.
<img width="842" alt="Screenshot 2024-01-01 at 20 42 35" src="https://github.com/benjaminjonard/koillection/assets/1164694/bb4efc1c-df09-4f79-aed6-8021c13a7616">

**Comment by ekamil** [comment]
I don't want to spam with a second issue but similar problem exists on a tag view
<img width="1403" alt="Screenshot 2024-01-01 at 21 02 06" src="https://github.com/benjaminjonard/koillection/assets/1164694/e76c586a-964f-47bc-b313-04288325b278">

I think even autogenerated images would work ok. Something random like gravatar, or like contacts apps - based on item's name.

**Comment by benjaminjonard** [comment]
Hi,

I added item names on related items. 
For the second issue, I added a new settings for displaying item names on grid view.
It will be available in the next release

**Comment by ekamil** [comment]
Thank you! 💜 Should I close the issue or do you want to keep it until release?
