### ISSUE TITLE
[Bug] Rating Display in List View

### ISSUE THREAD

**Issue by HackHerz** [koillection/koillection#1022]
So, I am using the rating field in a list view and it does not look right, as you may see in the following screenshot:

<img width="203" alt="Bildschirmfoto 2024-01-04 um 08 40 03" src="https://github.com/benjaminjonard/koillection/assets/2885148/940d7256-5411-4ad8-9256-ae0c404cd68f">

A quick look into the developer tools suggest that both FontAwesome icons for the _star_ and the _half-star_ are added. My guess is that these icons do not align? They look fine in the item view.

<img width="333" alt="Bildschirmfoto 2024-01-04 um 08 40 32" src="https://github.com/benjaminjonard/koillection/assets/2885148/d233be28-88dd-4634-9c18-11d56fcb5a91">

I am using Mac OS X 13.6.1 and Firefox 121. Can you reproduce that issue? Many thanks in advance, thus far I am enjoying your software a lot :)

**Comment by benjaminjonard** [comment]
I could reproduce and fix the issue, it will be fixed in the next release. Thanks !

**Comment by HackHerz** [comment]
With the new Release (v1.15.1) the overall look is much better, but the half stars do not align anymore. Neither in the item view:

<img width="164" alt="Bildschirmfoto 2024-01-09 um 13 14 41" src="https://github.com/benjaminjonard/koillection/assets/2885148/f1ca8a92-f6b3-49a1-ab58-b4834f69caa7">

or in the List View:

<img width="121" alt="Bildschirmfoto 2024-01-09 um 13 14 48" src="https://github.com/benjaminjonard/koillection/assets/2885148/ed688ec2-883b-4994-93b7-d519c536c31e">

**Comment by benjaminjonard** [comment]
This gets a bit tricky, this occurs only on some screen resolutions and zoom levels. I couldn't find a proper way to fix this.
I reworked the whole rating system, it should be better now. I'll make a new release by the end of the week

**Comment by HackHerz** [comment]
Thank you so much! I mean this has already been much better than before and i could definetely live with the Solution in 1.5.1.
