### ISSUE TITLE
[Bug] Tag Percentage is wrong

### ISSUE THREAD

**Issue by HackHerz** [koillection/koillection#1031]
So, the percentage in the Tag View seems to be wrong (or i simply do not get the use case?). Each of my items has only one tag associated.

<img width="511" alt="Bildschirmfoto 2024-01-08 um 10 48 01" src="https://github.com/benjaminjonard/koillection/assets/2885148/da360771-49cf-4984-a61c-ec8708406124">

---

What follows is my **attempt** to find the issue what causes a Tag to have more than 100% of items assigned. 

So the Tags Table seems to be rendered in `TagController` and the content stems from https://github.com/benjaminjonard/koillection/blob/c8ecbcbffff65d7a581e2784a5052bfcae69d007/src/Controller/TagController.php#L45

`$itemsCount` is used as the 100%. If i add more tags one can observe, that the percentages change. The math suggests that `$itemsCount` is in actuality the number of tags and not the total number of items? 

https://github.com/benjaminjonard/koillection/blob/c8ecbcbffff65d7a581e2784a5052bfcae69d007/src/Controller/TagController.php#L43

Since the `TagRepository` class does not implement the count method, it musst be inherited from `ServiceEntityRepository`?

This is where my quest came to an end. I guess (honestly, i have no clue) that either the items associated to tags need to be counted (but complicated due to deduplication) or the `$itemsCount` needs to be done on an `ItemRepository` object instead?

**Comment by benjaminjonard** [comment]
You are right, the `$itemsCount` must be done on the `ItemRepository`. 

I'll make a release soon to fix this, thanks !

**Comment by HackHerz** [comment]
Thank you!
