### ISSUE TITLE
[FR] Support videos as media source

### ISSUE THREAD

**Issue by risalt** [koillection/koillection#1038]
Hi! Thanks for this awesome software that you have put together!

I personally use it with several modifications as a frontend for my videogame collection. For each Item (videogame) I store several pieces of media (screenshots, box pictures, fanart, etc.). There's one particular type of media that I cannot store, which are the screenplays (videos, typically in MP4 format). If I try to upload one it doesn't work, neither it does if I overwrite the image field in the mysql database.

I know that lightgallery does support videos seamlessly, but a plugin lgVideo has to be activated apparently, and from a HTML tag perspective, the way to add a video item is different to the way to add an image. I have tried tinkering with the templates and the javascript files (modifying the Signatures object to hold videos), but I have been unsuccessful...

I think this is a feature very related to the intention of the platform and would be a great enhancement to it. Thanks in advance for your time if you decide to have a look at it!

![Screenshot from 2024-01-18 19-45-29](https://github.com/benjaminjonard/koillection/assets/42669571/bbdff7c9-2247-4b52-a939-33deb0d5af91)

**Comment by benjaminjonard** [comment]
Hi, 

Sure it seems like a good improvement.  I worked on a first version with a specific field type called 'Video'. 

![Screenshot from 2024-01-19 13-57-50](https://github.com/benjaminjonard/koillection/assets/20560781/30cce8f3-6bf5-4ccc-9024-d37c9b36b12f)

I could make the video playable directly from the image selection, but for some reason I couldn't get it to work inside lightgallery. I'll have another try later.
It needs a bit more polish but this first version will be available in the next release

**Comment by risalt** [comment]
Oh, that sounds awesome! I will certainly look forward to that new release, thanks a lot!  :smiley:

**Comment by risalt** [comment]
I have seen that you have updated the repo with the video capability, thanks a lot!
I have found two details:
* label.video is not translated. This is trivial to fix.
* The video does not open in the lightbox/lightgallery when clicking on it. To fix this, I had to substitute in template _content.html.twig:
`<div data-sub-html="{{ datum.label }}" data-slider-target="image" data-id="{{ datum.id }}"><div><video>...</video>...</div></div>`
with:
`<a data-video={{- '\'{"source":[{"src":"'}}{{ preload(asset(datum.video), {as: 'video'})|raw }}{{'","type":"video/mp4"}],"attributes":{"preload":true,"playsinline":true,"controls": true}}\'' }}
data-sub-html="{{ datum.label }}" data-slider-target="image" data-id="{{ datum.id }}"><div><video>...</video>...</div></a>`

This is explained in https://www.lightgalleryjs.com/demos/video-gallery/ . It is not perfect, as it only works with MP4 videos, but that's enough for me and it's probably an HTML5 limitation anyway.

**Comment by risalt** [comment]
Leaving this open in case the fix I refer above is to be included. Feel free to close it if you implement it or decide not to implement.

**Comment by benjaminjonard** [comment]
Thank you very much, somehow I missed that demo page... 
Videos now work in light gallery, for now it supports both mp4 and webm
