### ISSUE TITLE
[BUG] Running the last version as root in docker trigger a composer error

### ISSUE THREAD

**Issue by vyrtualsynthese** [koillection/koillection#1046]
Sorry I dont have the error at hand but container boostrap will crash on composer step 3 because of running container as root without COMPOSER_ALLOW_SUPERUSER="1" env variable.

You should update env variables documentation just in case.

**Comment by benjaminjonard** [comment]
I encountered the problem in my CI and other projects too. Apparently it is a new behavior from the latest composer version. I pushed a temporary fix, I'll see if I can find a better way to handle this.
