### ISSUE TITLE
[BUG] Filtering not working for grid view in 1.5.3

### ISSUE THREAD

**Issue by juancarlosmv** [koillection/koillection#1060]
Thanks for this software, it is the only one that fits my needs so well!

I recently updated my version of Koillection to 1.5.3. I really like having the name displayed together with the picture in grid view, but it seems that data-filter-target was moved to the parent div to include the text, but data-title remains in the child, which breaks the filtering functionality.

**Comment by benjaminjonard** [comment]
Thanks, the fix will be available in the next release

**Comment by juancarlosmv** [comment]
Thanks! It is working well now, I will close this.
