### ISSUE TITLE
Wishlist grid not working

### ISSUE THREAD

**Issue by Walter-o** [koillection/koillection#1069]
Setting "Display sub-wishlists in a grid" defaults to displaying a list regardless of the option.

![image](https://github.com/benjaminjonard/koillection/assets/33218378/906892f4-3726-4ab2-82c9-2a60256350cf)
![image](https://github.com/benjaminjonard/koillection/assets/33218378/c6a963bb-8833-472b-89d3-b03749a1b61b)

My configuration is:
docker-compose
postgres 16
koillection 1.5.6

**Comment by benjaminjonard** [comment]
This is because this settings is only for displaying nested wishlists ("sub-wishlists"), not wishes. If the grid view is also useful for wishes I will implement it
