### ISSUE TITLE
Collection price sum doesn't account for quantity

### ISSUE THREAD

**Issue by Walter-o** [koillection/koillection#1070]
Hello!

Given an item with a quantity of 2
that has a price of $20

And another item with a quantity of 2
with a price of $2

The sum at the info section above the collection shows the sum of the 2 prices: $22
while i expected the worth in total to be 44$.

I ended up storing values in text fields so i also disable the info field by proxy.

Also sorry for spamming issues, i just wanted to chart all the bugs/issues i could find.

**Comment by benjaminjonard** [comment]
Hello, this will be resolved in the next release

Thanks for reporting this
