### ISSUE TITLE
Data for item disappears if I add a field to the template it uses

### ISSUE THREAD

**Issue by dodancs** [koillection/koillection#1072]
Hey, first of all, love the software! I can see many ways of improving it, and maybe once I have some spare time, will try to contribute!

The issue I discovered recently when organizing my Vinyl collection really slowed me down. I created a semi-complete template for a new collection called Vinyls. Then, I added a record to it, and after that I realized I want to store more information about them, so I edited the template, and (I think it was only after) I pressed the button to load attributes from the template on an existing record, and added new info, but I noticed, all of the data I entered previously disappeared! Only the title remained.

It seems like when the template for a collection is changed, and you edit an item that was created before the template change, then all of the data just vanishes from all of the items that used the template previous to the template change. I have not had time to debug this further, I just wanted to open this issue and describe the symptoms as best as I can.

If I find the time, I will create just a temporary instance and try to figure out when exactly this is happening, but I am for sure not going to test this on my "prod" instance, because I do not want to lose any more progress.

Anyone came across the same issue? Thanks!

**Comment by benjaminjonard** [comment]
Hi, 

If I understand correctly, the steps to reproduces are :
1 - Create a template with some fields
2 - Add an item using this template
3 - Add a new field to the template
4 - Reapply the template to the item 

It seems I cannot reproduce this issue, would you mind sharing the template you are using ? Also could you check in the browser inspector if there is any javascript error ?
