### ISSUE TITLE
Inventory not using selected collections

### ISSUE THREAD

**Issue by sanmadjack** [koillection/koillection#1079]
I'm using 1.5.6 via docker. When I try to create an inventory just for a particular collection, the resulting inventory includes all items from all of my collections. I expect that it will only create an inventory for the selected collection(s).

**Comment by benjaminjonard** [comment]
Hello, it should be fixed in latest release ([1.5.7](https://github.com/benjaminjonard/koillection/releases/tag/1.5.7))

**Comment by sanmadjack** [comment]
Confirmed is resolved. Thanks.
