### ISSUE TITLE
After most recent update, unable to type into choice list fields to find desired option

### ISSUE THREAD

**Issue by openstampede** [koillection/koillection#1112]
Hello.

Following the most recent update, I am no longer able to type into choice list fields in order to find the choice I want. This used to be possible with at least the Country field. Now, the only way to select a country is to scroll through the list manually. I've tested this on both Firefox and Safari.

Happy to provide more detail if needed.

Side note: Koillection is fantastic and something I've wanted for a very long time. Thank you so much for your work on it! I couldn't find a donation link anywhere, but please share it if you have one. :)

**Comment by openstampede** [comment]
Correction: It seems that the only choice list field that can't be typed into now is the Country field. I can type into the others.

**Comment by benjaminjonard** [comment]
Hello, I've identified the issue, and it will be fixed in the next release (which will likely be available next week). 

Thanks for your kind words. I currently don't have a donation link, but I'll consider adding one since you're not the first person to ask.
