### ISSUE TITLE
Clicking on link doesn't work

### ISSUE THREAD

**Issue by cvpsmith** [koillection/koillection#1113]
Running the Gitpod demo.  Created a collection and an item with a web link using the "Add Field: Link" function.  When you go to view the item, clicking on the link does nothing.  Is this a limitation of Gitpod/container deployment, or does this functionality not work?  TIA...

**Comment by benjaminjonard** [comment]
It seems to be a Gitpod limitation, I can click links on my instance

**Comment by cvpsmith** [comment]
Ah, okay.  Thanks!

**Comment by cvpsmith** [comment]
I'll try a regular instance.  Great software btw!
