### ISSUE TITLE
Redirect for wish list does not work

### ISSUE THREAD

**Issue by McSchweiz1886** [koillection/koillection#1114]
When i add a link to my whislist items and click on it in the preview it rout me to the wishlist instead of the real url.

Example:

Should go to:
www.google.com
Where i end:
https://mykoillection.com/wishlists/www.google.com

**Comment by benjaminjonard** [comment]
The problem is that HTML links require the url to start with the protocol (http://) otherwise the browser doesn't consider the link to point to another website.

I'll see what I can do, a quick fix for you would be to add https:// at the beginning of your url
