### ISSUE TITLE
Private price fields still contribute to total in Info section of Collection page

### ISSUE THREAD

**Issue by openstampede** [koillection/koillection#1122]
To reproduce:

1. Create a public item in a public collection under a public profile.
2. Create a "price" field and set it to private (either manually or via a template)
3. Save the item

Behavior:

The price field isn't shown for the item but contributes to the total in the Info section of the collection page.

Expected behavior:

Either it should not contribute to the total or it should be possible to set the total on the Collection page to private. 

(Note: Being able to turn off that total, or at least hide it from public view, is something I'd really love to see. I'd be happy to submit a separate feature request if needed.)

**Comment by benjaminjonard** [comment]
Hello, for now I fixed the problem, private prices fields won't contribute anymore to total. The fix will be available in the next release.

I'll try to add an option to hide the total a bit later
