### ISSUE TITLE
Could not open public item

### ISSUE THREAD

**Issue by jonas-dev** [koillection/koillection#1136]
Hello,
I have added an item to a collection that uses a template with public and internal fields. If I share the link of the collection with a user who is not logged in, they can access the item via the URL. If they find the item via the search and click on the exact same item, they will be redirected to the login form.

**Comment by benjaminjonard** [comment]
Hello, the links on the shared search page will be fixed in the next release

**Comment by benjaminjonard** [comment]
Hello, it was fixed in the last release
