### ISSUE TITLE
[Feature Request] Link to tag page when using list fields

### ISSUE THREAD

**Issue by JetpackCat-IT** [koillection/koillection#1147]
Hello,
I noticed that when you write a Tag in a custom text field it becomes a clickable link that redirects to the tag page
![image](https://github.com/benjaminjonard/koillection/assets/27817700/831dc88f-acbf-41e6-9ec7-01104b1d7d4f)

But this doesn't happen when using lists
![image](https://github.com/benjaminjonard/koillection/assets/27817700/32cb42d3-5620-43ae-aeb3-f0aef9ff9034)

As you can se the field "Personaggio" becomes a link, but not the field "Origine"

It would be nice to have this feature also with list fields

**Comment by benjaminjonard** [comment]
Hello, this was fixed in the last release
