### ISSUE TITLE
Price (price) is not a valid choice for type.

### ISSUE THREAD

**Issue by azuravian** [koillection/koillection#1152]
When adding data to an item using the API, it is impossible to add price data.  All other types are added by their name in lowercase.  I have tried using both "price" and "Price" as the type of the new data being added.  I get the same message I would get if I put gibberish as the type:

`{
	"@id": "\/api\/validation_errors\/8e179f1b-97aa-4560-a02f-2a8b42e49df7",
	"@type": "ConstraintViolationList",
	"status": 422,
	"violations": [
		{
			"propertyPath": "type",
			"message": "The value you selected is not a valid choice.",
			"code": "8e179f1b-97aa-4560-a02f-2a8b42e49df7"
		}
	],
	"detail": "type: The value you selected is not a valid choice.",
	"hydra:title": "An error occurred",
	"hydra:description": "type: The value you selected is not a valid choice.",
	"type": "\/validation_errors\/8e179f1b-97aa-4560-a02f-2a8b42e49df7",
	"title": "An error occurred"
}`

**Comment by benjaminjonard** [comment]
This is bug it will be fixed in the next release, it should be available in a few days.

**Comment by azuravian** [comment]
Thank you.  That will be fantastic.

**Comment by benjaminjonard** [comment]
Hello, it should work now
