### ISSUE TITLE
[Bug] Arrow Key URI binds conflict

### ISSUE THREAD

**Issue by azuravian** [koillection/koillection#1159]
When in a collection, I can click on an item and open that item to view.
At that point, I can use the left and right arrow keys on my keyboard to navigate to the previous or next item in the collection, respectively.

When I click on a thumbnail associated with an item to view the larger image, if I use the right and left keyboard arrows, it looks like it would do the same thing with images, but the functionality for the items in a collection is also still turned on.
This results in the image starting to slide over to the next image, then the page goes away and it loads the next item in the collection.

I think when in the image viewer, the keyboard functionality to go to the next collection item should be disabled.

**Comment by risalt** [comment]
I agree with this, it happens to me all the time!
