### ISSUE TITLE
Migrating up to App\Migrations\Postgresql\Version20240411083531 error

### ISSUE THREAD

**Issue by thomas-333** [koillection/koillection#1191]
I've noted the following in my docker logs:

```
[notice] Migrating up to App\Migrations\Postgresql\Version20240411083531
[notice] Migration App\Migrations\Postgresql\Version20180731115129 skipped during Execution. Reason: "Migration can only be executed safely on 'postgresql'
```

The last line appears multiple times. I'm using Mariadb for my database and not Postgresql. Koillection seems to be running fine. 

Can I just ignore the messages?

**Comment by benjaminjonard** [comment]
Hello, yes those messages can be safely ignored. I probably need to find a way to hide them as they are misleading
