### ISSUE TITLE
Error 1.5.14 -> 1.5.15

### ISSUE THREAD

**Issue by CrowMash** [koillection/koillection#1250]
I just upgraded Koillection to 1.5.15 but now I got this error :

```
Doctrine\DBAL\Exception\ConnectionException:
An exception occurred in the driver: SQLSTATE[08006] [7] could not translate host name "postgresql" to address: Name or service not known

  at vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77
  at Doctrine\DBAL\Driver\API\PostgreSQL\ExceptionConverter->convert()
     (vendor/doctrine/dbal/src/Connection.php:1373)
  at Doctrine\DBAL\Connection->handleDriverException()
     (vendor/doctrine/dbal/src/Connection.php:1321)
  at Doctrine\DBAL\Connection->convertException()
     (vendor/doctrine/dbal/src/Connection.php:219)
  at Doctrine\DBAL\Connection->connect()
     (vendor/doctrine/dbal/src/Connection.php:762)
  at Doctrine\DBAL\Connection->executeQuery()
     (vendor/doctrine/orm/src/Persisters/Entity/BasicEntityPersister.php:863)
  at Doctrine\ORM\Persisters\Entity\BasicEntityPersister->count()
     (vendor/doctrine/orm/src/EntityRepository.php:140)
  at Doctrine\ORM\EntityRepository->count()
     (vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryProxy.php:86)
  at Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepositoryProxy->count()
     (src/Controller/SecurityController.php:24)
  at App\Controller\SecurityController->login()
     (vendor/symfony/http-kernel/HttpKernel.php:183)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:182)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:29)
  at require_once('/var/www/koillection/vendor/autoload_runtime.php')
     (public/index.php:5)    
```

Tell me if you need any information about my installation (docker-compose, env).

**Comment by benjaminjonard** [comment]
Hello, it may be that the postgres container isn't starting properly. Could you check if there is any logs for this container (with `docker compose logs -f postgres`)

One common reason could be that the Postgresql container updated itself to a newer major release, but major version aren't compatible with each other

**Comment by CrowMash** [comment]
My container is not "postgres" but "db" (I used your docker-compose.yml) and if I run `docker compose logs -f db` it shows that :
```
db  | 2024-11-29 14:58:34.559 UTC [1] LOG:  starting PostgreSQL 16.6 (Debian 16.6-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db  | 2024-11-29 14:58:34.632 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db  | 2024-11-29 14:58:34.632 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db  | 2024-11-29 14:58:34.641 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db  | 2024-11-29 14:58:34.683 UTC [29] LOG:  database system was shut down at 2024-11-29 13:35:31 UTC
db  | 2024-11-29 14:58:34.740 UTC [1] LOG:  database system is ready to accept connections
```

**Comment by stanrc85** [comment]
I'm having similar issues after updating this morning. Webpage just loads a SQL error log 
![Screenshot_20241129-102018](https://github.com/user-attachments/assets/69c6c07d-6569-4677-aed7-0bf708599a22)

**Comment by CrowMash** [comment]
I have this in my .env file :
```
########################################################################################################
#                                                DATABASE
########################################################################################################

DB_DRIVER=pdo_pgsql
DB_NAME=koillection
DB_HOST=db
DB_PORT=5432
DB_USER=koillection
DB_PASSWORD=*****
DB_VERSION=16
```

**Comment by benjaminjonard** [comment]
There is a new docker image building, it should be available in around 1 hour.
Something weird happened when building the docker image with the latest version of Ubuntu, I reverted it and hope it fixes the issue

**Comment by xayazu** [comment]
Same problem here, "An exception occurred in the driver: SQLSTATE[08006] [7] could not translate host name "postgresql" to address: Name or service not known". I'm using postgres 17 and worked until this update.

Edit
> There is a new docker image building, it should be available in around 1 hour. Something weird happened when building the docker image with the latest version of Ubuntu, I reverted it and hope it fixes the issue

Thanks a lot.

**Comment by xayazu** [comment]
Using the new image im getting 

> 2024-11-29T18:06:32.955126255Z **** 11/11 - Setup complete, starting the server. ****
> 2024-11-29T18:06:34.234667724Z [29-Nov-2024 18:06:34] ERROR: unable to bind listening socket for address '/run/php/php8.4-fpm.sock': No such file or directory (2)
> 2024-11-29T18:06:34.234740740Z [29-Nov-2024 18:06:34] ERROR: FPM initialization failed

and the container get stuck,

Edit:
I deleted the stack, changed some variables to plain text and now its working.

**Comment by CrowMash** [comment]
I just pulled the last build and it's working great!

**Comment by PerpSearch** [comment]
What'd you change if I may ask. Mine is still screwed.

**Comment by xayazu** [comment]
> What'd you change if I may ask. Mine is still screwed.

Just changed image to "latest", before i had it in a variable too, the PHP_TZ to plain text and APP_DEBUG to 0 and worked again.

**Comment by PerpSearch** [comment]
That's too strange.  We clearly have different set ups.  I tried changing
it from koillection/koillection to koillection/latest and I get an error
right out of the box that says  . . .  " koillection Pulling koillection
Error pull access denied for koillection/latest, repository does not
exist"  My PHP_TZ has always been in pain text and I don't seem to have a
variable  APP_DEBUG in my build.  Back to the drawing board I guess.
Thanks though.

**Comment by benjaminjonard** [comment]
@PerpSearch I think the correct syntax would be koillection/koillection:latest but it should be equivalent to just koillection/koillection 

Could you try to force docker to pull the image with `docker compose pull` ?

**Comment by PerpSearch** [comment]
I've been working on this in various trouble shooting strategies for the last 6 hours the most recent of which was to start from scratch and create new empty folders rather than my existing database. I'll try the change right now and we'll see. I know you're in a different time zone, but it's 130am here so I'm not sure how much longer I can go.

**Comment by PerpSearch** [comment]
Ok as I said I started with a blank slate and gave it a run, but while I was writing my last response it started working, but with zero records.   Next question is how to get them all back in. Any thoughts on that? I cannot lose that stuff.

**Comment by benjaminjonard** [comment]
@PerpSearch just in case, I answered you there https://github.com/benjaminjonard/koillection/discussions/1249 so we do not spam notifications here
