### ISSUE TITLE
[Bug] api/authentication_token returns empty string token.

### ISSUE THREAD

**Issue by junpet** [koillection/koillection#1265]
Koillection v1.5.16 (docker).
Calling endpoint `api/authentication_token` returns the following:
```json
{
  "token": ""
}
```
I've tried in javascript, curl and on the API documentation page of my Koillection instance.

**Comment by benjaminjonard** [comment]
Could you try to run this command inside your Koillection container ? 

`php bin/console lexik:jwt:generate-key --overwrite`

**Comment by junpet** [comment]
I replied in email yesterday, but it looks like my comment doesn't appear.
Your command helped. Now I can generate auth token. Thanks!
