### ISSUE TITLE
Names in Public Grid View

### ISSUE THREAD

**Issue by iawa2k** [koillection/koillection#1268]
Docker Image on UnRAID (latest)

Koillection version: 1.5.16
PHP Version: 8.4.1
Symfony Version: 7.1.8
API Platform Version: 4.0.9
Opcache: Enabled

Names do not appear in the Public view of a collection when in Grid mode, is there an option to enable this?

![1](https://github.com/user-attachments/assets/c6d9516a-3ac2-4fd3-b9bd-e05326eb9fcf)
![2](https://github.com/user-attachments/assets/9f4f5b2d-5c35-43ca-bf88-412294de021d)

**Comment by benjaminjonard** [comment]
It should work with the latest release (1.6.0), it will use the collection's owner settings to display item's name.

**Comment by iawa2k** [comment]
> It should work with the latest release (1.6.0), it will use the collection's owner settings to display item's name.

Just installed and works great. Many thanks!
