### ISSUE TITLE
ERROR: unable to bind listening socket for address '/run/php/php8.4-fpm.sock': No such file or directory (2)

### ISSUE THREAD

**Issue by junpet** [koillection/koillection#1270]
After upgrading to v1.6.0 I got the following error. I use docker.

```
koillection  | 2024-12-29T13:43:21.811233985Z **** 11/11 - Setup complete, starting the server. ****
koillection  | 2024-12-29T13:43:21.997279332Z [29-Dec-2024 13:43:21] ERROR: unable to bind listening socket for address '/run/php/php8.4-fpm.sock': No such file or directory (2)
koillection  | 2024-12-29T13:43:21.997348672Z [29-Dec-2024 13:43:21] ERROR: FPM initialization failed
```

**Comment by maxkratz** [comment]
Same on my system.

**Comment by PerpSearch** [comment]
I'm getting that as well, but I suspect it's because 1.6.0 requires PHP 8.4 and my system is running 8.2
Until Synology releases 8.4 I may be screwed for a while and have to stick to 1.5.16

**Comment by maxkratz** [comment]
> I'm getting that as well, but I suspect it's because 1.6.0 requires PHP 8.4 and my system is running 8.2 Until Synology releases 8.4 I may be screwed for a while and have to stick to 1.5.16

Do you use Docker to run v1.6.0 on your Synology NAS?

AFAIK, PHP is part of the Docker image.

**Comment by PerpSearch** [comment]
yes, I'm running it a docker container

**Comment by maxkratz** [comment]
> yes, I'm running it a docker container

In this case, the PHP version of your Synology OS/package should not be relevant

**Comment by PerpSearch** [comment]
Well that's good to know.  Give me hope since I obviously lack the
technical expertise to fix it. I figured since the release notes said it
required 8.4 then I better have 8.4 and if it were up to Synology to
release a new version we could be here for a while. Thanks for the insight.

**Comment by lgwapnitsky** [comment]
getting the same on a docker installation. php is NOT installed on the host

**Comment by benjaminjonard** [comment]
A new docker image was just published, running `docker compose pull` and `docker compose up -d` should fix the issue

**Comment by PerpSearch** [comment]
That got it running.  Errors are showing up in the admin panel we'll take
more about that off line

**Comment by junpet** [comment]
Thank you for the fix.

**Comment by maxkratz** [comment]
Thank you, the new Docker image also fixed the error for me.
