### ISSUE TITLE
Docker container not starting

### ISSUE THREAD

**Issue by Surgical71** [koillection/koillection#548]
Hi All

I installed Koillection via Portainer stack (Docker-Compose). DB is up and running with no issues but the Koillection container starts and then keeps running but gives the following error and I cant connect:

**** 5/13 - Configure https ****
**** 6/13 - Migrate the database ****
PHP Fatal error:  Uncaught Symfony\Component\Dotenv\Exception\FormatException: A value containing spaces must be surrounded by quotes in "/var/www/koillection/.env.local" at line 3.
...pgsql (or pdo_mysql)\nDB_NAME=koillection...
                      ^ line 3 offset 59 in /var/www/koillection/vendor/symfony/dotenv/Dotenv.php:550

Stack trace:
#0 /var/www/koillection/vendor/symfony/dotenv/Dotenv.php(371): Symfony\Component\Dotenv\Dotenv->createFormatException()
#1 /var/www/koillection/vendor/symfony/dotenv/Dotenv.php(248): Symfony\Component\Dotenv\Dotenv->lexValue()
#2 /var/www/koillection/vendor/symfony/dotenv/Dotenv.php(560): Symfony\Component\Dotenv\Dotenv->parse()
#3 /var/www/koillection/vendor/symfony/dotenv/Dotenv.php(115): Symfony\Component\Dotenv\Dotenv->doLoad()
#4 /var/www/koillection/vendor/symfony/dotenv/Dotenv.php(148): Symfony\Component\Dotenv\Dotenv->loadEnv()
#5 /var/www/koillection/vendor/symfony/runtime/SymfonyRuntime.php(107): Symfony\Component\Dotenv\Dotenv->bootEnv()
#6 /var/www/koillection/vendor/autoload_runtime.php(17): Symfony\Component\Runtime\SymfonyRuntime->__construct()
#7 /var/www/koillection/bin/console(11): require_once('...')

}
  thrown in /var/www/koillection/vendor/symfony/dotenv/Dotenv.php on line 550

Thanx

**Comment by benjaminjonard** [comment]
Hello, I think you need to update your docker-compose.yml and update the environment variables for the Koillection container.
You have to choose the correct values for `DB_DRIVER`, `DB_PORT`,  `DB_VERSION` and `HTTPS_ENABLED`

**Comment by Surgical71** [comment]
Okay yeah my own fault sorry. Danke
