### ISSUE TITLE
Tags missing after creation

### ISSUE THREAD

**Issue by Surgical71** [koillection/koillection#549]
Hi Again

It seems like after I create a tag for an item and save it the tag go's missing. Is there something I am doing wrong?

Creating tag:
![image](https://user-images.githubusercontent.com/80483431/195612218-c2685236-859f-438f-a03f-41bc6b853707.png)

Tag missing after saving tag:
![image](https://user-images.githubusercontent.com/80483431/195612337-52bd7652-f548-4268-9793-a618079b8cf9.png)

No tags:
![image](https://user-images.githubusercontent.com/80483431/195612380-ba0cb805-e5a9-477a-b100-a4c0660983e5.png)

Danke

**Comment by benjaminjonard** [comment]
Hello again, you have to press enter to add the tag to the item.
I probably need to find a way to make that more intuitive

**Comment by Surgical71** [comment]
Haha thanx man. I am sorry for all the questions. Just found this app and created it for my GF for her photocard collection lol.

I managed to create the tags, but when I click on tags on the left and then click on a tag to view I get the following error:
![image](https://user-images.githubusercontent.com/80483431/195624598-b60457d7-9d30-4f34-a9b1-f3a3c68fd551.png)

**Comment by benjaminjonard** [comment]
I found the problem. I'm planning to make a new release tomorrow, it should fix this error

**Comment by Surgical71** [comment]
> I found the problem. I'm planning to make a new release tomorrow, it should fix this error

Thank you for your effort. Will let you know if issue is resolved once the new release is out :)

**Comment by Surgical71** [comment]
Issue resolved with new version. Thanx a lot @benjaminjonard
