### ISSUE TITLE
Modify User Storage Limit

### ISSUE THREAD

**Issue by DebugDax** [koillection/koillection#560]
Hello,

I am currently using the docker release and don’t see a way to change a users storage quota. Currently it seems hard coded to 512mb, but I would like to increase the limit to 1gb+. 

Is there a way to modify this, and if not could an admin setting be added to the interface for it?

Thanks!

**Comment by benjaminjonard** [comment]
Hello, you can change this setting for each users. In the Administration page, click on the "Users" panel and then edit a user. There you should find a property called "Disk space allowed" (in bytes)

**Comment by DebugDax** [comment]
Ah, I see!

sorry for the pointless issue being opened. I don’t want signed in as an admin so didn’t realize the option already exist. 

Got it now, thank you!
