### ISSUE TITLE
[Feature Request] Filter by everything

### ISSUE THREAD

**Issue by bacsom** [koillection/koillection#575]
We have a digital movie database in our school. Now the teachers use a big excel file to find films for their classes. Koillection would be a fantastic upgrade since it is fast and supports mobile phones and tags. The only feature I miss is the option to filter by different things, like tags, and labels. Is it possible to add this in a future release?

**Comment by benjaminjonard** [comment]
Hello, the search function already search by labels, I could make it search by tags too.

I think you are referring to the "Filter by name" input in collections thought. Its purpose is to quickly find items inside big collections. I think the search function should be used for more complex queries.
