### ISSUE TITLE
REST API data fields

### ISSUE THREAD

**Issue by bodak** [koillection/koillection#582]
I am trying to programatically add a lot of items with custom data fields (from templates), but can't seem to find a way to do this using the REST API.

Are additional data fields supported in the current version?

Working example from the API docs below
```
{
  "name": "string",
  "quantity": 1,
  "collection": "string",
  "tags": [
    "string"
  ],
  "relatedItems": [
    "string"
  ],
  "file": "string",
  "visibility": "public"
}
```

**Comment by bodak** [comment]
@benjaminjonard Apologies to tag you on this, but would be helpful to know if custom data fields are possible through the API. This would help greatly with integration with Goodreads, Trakt.tv, etc.

**Comment by benjaminjonard** [comment]
Hello, yes they are available but for now it has to be done in 2 steps : 

First create your item using `/api/items`

```
{
  "name": "LotR #1",
  "quantity": 1,
  "collection": "/api/collections/86f2580a-2180-47bf-a81d-1745c1de7579",
  "visibility": "public"
}
```
In the response you will get the id of the item newly created (for this exemple it is `accad242-09c5-4d07-ae4f-64daf6e220ab`)


Then you can add your data with `/api/data` using the item id
```
{
  "item": "/api/items/accad242-09c5-4d07-ae4f-64daf6e220ab",
  "type": "text",
  "label": "Author",
  "value": "Tolkien",
  "position": 0
}
```
