### ISSUE TITLE
Cannot add Thumbnails

### ISSUE THREAD

**Issue by angelo-melis** [koillection/koillection#621]
Hi,

I just started to play with Koillection and I like what I see. But trying to create a collection and add a thumbnail fails for me. I think I am just missing something obvious, but I cannot figure out what I am doing wrong. I am running Koillection in Docker and I can create a  collection, but when adding a thumbnail I get the error: Oops, a critical error occurred :(.

When looking at the logs I see:
{"message":"Uncaught PHP Exception Symfony\\Component\\HttpFoundation\\File\\Exception\\FileNotFoundException: \"The file \"tmp/col_63946cb45b827.png\" does not exist\" at /var/www/koillection/vendor/symfony/http-foundation/File/File.php line 36","context":{"exception":{"class":"Symfony\\Component\\HttpFoundation\\File\\Exception\\FileNotFoundException","message":"The file \"tmp/col_63946cb45b827.png\" does not exist","code":0,"file":"/var/www/koillection/vendor/symfony/http-foundation/File/File.php:36"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2022-12-10T11:25:40.375152+00:00","extra":{}}

I get it that it cannot find the thumbnail (I try to add it from the browser on my mac), but how do I add the thumbnail?

Thanks and kind regards

**Comment by angelo-melis** [comment]
Funny thing is that images added to items does work. No problems there

**Comment by benjaminjonard** [comment]
Hello, 

When uploading a thumbnail, it is temporary saved in this folder ./public/tmp/ . For some reasons it looks like it can't be written there.
Are you using Docker to run Koillection ?

**Comment by angelo-melis** [comment]
Yes, I am using Docker.

**Comment by angelo-melis** [comment]
It looks like it was related to the rights on the tmp folder. I changed it and now it does work.

**Comment by benjaminjonard** [comment]
Ok great, I'll have a look to the docker image to see how to prevent that
