### ISSUE TITLE
Variables from .env are not loaded in the container.

### ISSUE THREAD

**Issue by Coukaratcha** [koillection/koillection#660]
Environment variables in `.env` file are not loaded by koillection container. You need to write them in `docker-compose.yml` in `environment` section, including sensible data as database's credentials.

So if you want to put your `docker-compose.yml` in a repository, you must publish such critical data as well; which is bad, even for a private repository.

For database container (postgres or mysql), you can load variables from the `.env` file, so I assume it's possible.

Thank you for your work.

**Comment by benjaminjonard** [comment]
Hello, 

I updated the docker container to support the use of a .env file. If you pull the latest image it should work.
