### ISSUE TITLE
First user created is not admin

### ISSUE THREAD

**Issue by Afaren57** [koillection/koillection#667]
Hello, few month ago, I decided to install koillection and start using it to list all my library. After wanting to create another user to share it with someone, I realized I couldn't find the action because I wasn't admin. Looking at the wiki, the first user created (me) should be admin. I tried to install it again from scratch, got it working and again, my first user created is not admin (and I would have need to do it all again, as it's on a fresh new database).

I may have an idea of what could have been causing it, when I tried to create the first user, I had an error while doing it and had to restart container to create it again. Maybe it couldn't create the admin the first time and created a simple user the second time. Problem is, I have no admin user so I am limited. If there is anything to convert the user of my first koillection instance, it would be nice so I wouldn't need to redo everything I've already done in koillection.

**Comment by benjaminjonard** [comment]
Hello, 

Right now you best option would be to update the user directly in your database. The `roles` column for your user should contain `a:2:{i:0;s:9:"ROLE_USER";i:1;s:10:"ROLE_ADMIN";}`
I will try to reproduce, or I will add a command that can create users from command line just in case this happens.


If you have some time to spare, could you activate the debug mode and see what error you get ? (add this environment variable to your docker-compose : APP_DEBUG=1)

**Comment by vyrtualsynthese** [comment]
Hello same problem here on new docker install.

a:2:{i:0;s:9:"ROLE_USER";i:1;s:10:"ROLE_ADMIN";

In the DB but shown as role user on the app.

**Comment by vyrtualsynthese** [comment]
More info with debug activated

```[12-Jan-2023 17:15:26] NOTICE: PHP message: PHP Warning:  Can't preload already declared class ReflectionEnum in /var/www/koillection/vendor/laminas/laminas-code/polyfill/ReflectionEnumPolyfill.php on line 8```

and no more logs after that.
No errors in browser.

Sorry but I am limited in PHP and cannot add more to this.

Didn't find any work around.

I am pretty exited about this app to manage my ever growing collections !
Keep doing great work

**Comment by benjaminjonard** [comment]
I found the issue (actually 2 issues).

Everything is fine concerning your user, but the role isn't properly displayed.
You can't create a new user because I made a bad copy-paste apparently at some point and removed the button... You should be able to go to `/admin/users/add` to create your new user right now.

I fixed both problems, I'll publish a release tomorrow

**Comment by Afaren57** [comment]
Nice, I didn't yet had the time to do what you asked yesterday that the issue is already found. I'm looking forward your update. I successfully created another user by modifying the link as you sayed, many thanks.

By the way, with this issue I was thinking of reinstalling it with a new database and I realized you could export it with the web interface but there is no way to import it in another koillection. Should I create a new issue for this ? It could be helpful if you have a problem some day or whatsoever.

**Comment by vyrtualsynthese** [comment]
working fine for me.
