### ISSUE TITLE
500 error with big files

### ISSUE THREAD

**Issue by vyrtualsynthese** [koillection/koillection#760]
I am getting 500 error when uploading aboce 20M file.
I think it had to do with php.ini max_upload size.

The error could be more explanatory.

As I am using the docker image I created the linked issue : https://github.com/koillection/koillection-docker/issues/2

I am trying to reproduce and will post logs.

**Comment by benjaminjonard** [comment]
Hello, indeed 20M+ files will make the request fail because of the php.ini file.

I'll add an env variable for the next release to easily change that parameter

**Comment by vyrtualsynthese** [comment]
Thats great. Thanks.
