### ISSUE TITLE
500 error with /api/authentication_token

### ISSUE THREAD

**Issue by stirosthegreat** [koillection/koillection#765]
New docker install, trying to use the api to import my current collection. When I go to authenticate, I get a 500 error. It seems to know when I enter invalid credentials so I'm assuming that it's only when it tries to return the jwt token. I also can't seem to find the log files to upload.

**Comment by benjaminjonard** [comment]
Hello, if you set the env variable `APP_DEBUG` to 1 it should give more information about the error

**Comment by stirosthegreat** [comment]
thank you, the error I got was "Attempted to load class "WebProfilerBundle" from namespace Symfony\Bundle\WebProfilerBundle". Did you forget a "use" statement for another namespace?" I uploaded a text file containing the html code that postman produced with the full error details. Github wouldn't allow me to just uploaded the html file. 
[debug_response.txt](https://github.com/koillection/koillection/files/11083790/debug_response.txt)

**Comment by duhow** [comment]
```php
Symfony\Component\ErrorHandler\Error\ClassNotFoundError:
Attempted to load class "WebProfilerBundle" from namespace "Symfony\Bundle\WebProfilerBundle".
Did you forget a "use" statement for another namespace?

  at /var/www/koillection/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php:126
  at App\Kernel->registerBundles()
     (/var/www/koillection/vendor/symfony/http-kernel/Kernel.php:331)
  at Symfony\Component\HttpKernel\Kernel->initializeBundles()
     (/var/www/koillection/vendor/symfony/http-kernel/Kernel.php:708)
  at Symfony\Component\HttpKernel\Kernel->preBoot()
     (/var/www/koillection/vendor/symfony/http-kernel/Kernel.php:172)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (/var/www/koillection/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (/var/www/koillection/vendor/autoload_runtime.php:29)
  at require_once('/var/www/koillection/vendor/autoload_runtime.php')
     (/var/www/koillection/public/index.php:5)                
```

**Comment by benjaminjonard** [comment]
Hello, do you have your `APP_ENV` env variable set to `dev` ? If so changing this to `prod` should solve this issue.
