### ISSUE TITLE
Wiki installation guide for MySQL

### ISSUE THREAD

**Issue by punfil** [koillection/koillection#772]
Hi!

Today, I was deploying Koillection on a VM using MySQL and noticed that installation tutorial (https://github.com/koillection/koillection/wiki/Installation) proposes:
```
# - MYSQL_USER=root
```
which seems to be obsolete and causes an error.
The `compose up` process finishes successfully without this line and the Koillection works fine.
Also, I've noticed that in file `docker-compose.dist.yml` it has been already deleted (there is a trailing new line left in place where it most likely was).

Greetings,
punfil

**Comment by benjaminjonard** [comment]
Hello,

Yes you are right,  I updated the wiki.

Thanks
