### ISSUE TITLE
Renaming Sub-collections not working

### ISSUE THREAD

**Issue by mephisto3478** [koillection/koillection#782]
Hey!
First of all: Thanks to all contributors for this awesome piece of software!

I use it to keep track of my physical manga releases and created a collection for it.
Now, for each Series I want a sub-collection containing each volume as an item.

But when I try to rename the field "Sub-collections section label" under "Edit collection Physical Manga" to something like "Series" it won't change and still display "Sub-collections" no matter what I try.

Am I doing anything wrong or is it the software not working as intended?

Thanks for any help!

**Comment by mephisto3478** [comment]
Same goes for the Item section label

**Comment by benjaminjonard** [comment]
Hello, you are right there is a bug. I'll fix it and publish a new release in a few days
