### ISSUE TITLE
[Feature Request] Ability to add custom CSS

### ISSUE THREAD

**Issue by phampyk** [koillection/koillection#811]
First of all a big THANK YOU for creating this. Is the thing I didn't know I needed, after so many years I can finally have my collection of knitting and sewing patterns organized, searchable and easy to skim through. 

I would only want to ask if there's any possibility to add a custom CSS box somewhere. 

I know that make a whole customizable interface can be a bit of a big task, so maybe just adding the option to customize by CSS can be a bit easier, not sure if it's difficult to implement, so i understand if it's a big ask, but I do love to customize what I host to have more of a cohesive look between apps (also I'm a big sucker for the dracula color scheme lol)

Thank you!

**Comment by benjaminjonard** [comment]
Hello, I'm currently reworking the light and dark themes files. After that it should be a bit easier to add custom themes using those files as a starting point. 

When it's ready I'll try to add a custom CSS box

**Comment by phampyk** [comment]
That's amazing news, I can't wait!!

Thank you!

**Comment by benjaminjonard** [comment]
Custom CSS is available with the latest release (in the configuration panel on the Administration page)

I'd be interested to know if that works well for you

**Comment by phampyk** [comment]
I just had to try it and works great!!
One thing tho, the profile picture menu shows white background when I'm on dark mode, with and without the css editing, idk if that's intended or just missing.
But yeah, pretty much amazing!! thank you so so so much!

**Comment by benjaminjonard** [comment]
Sorry for the late response. 
For the avatar the background color is randomly assigned at user creation, you should probably be able to override it with CSS.

Would you mind sharing your theme CSS ? I'd like to add a wiki page with community created themes

**Comment by phampyk** [comment]
Hi!! the CSS is for a dark theme only, with [dracula](https://draculatheme.com/contribute) colours https://pastebin.com/bMFwCd7f

About the "avatar background" it wasn't the avatar itself, but the menu dropdown. I figured out is just de div ".dropdown-menu li" and did a bit of a change so the dropdown menu has the same background colour as the website (as with a dark theme I think a flashy pure white drop down menu is a no no lol) 

I put this code 
` .dropdown-menu {
  border: 1px solid var(--font-color-light);
}

.dropdown-menu li{
background-color: var(--background-color-dark);
border-bottom: var(--background-color-dark);
border-bottom-color: var(--background-color-dark);
} `

Maybe something to change for the dark theme in general? so the dropdown is not white?

Thank you so much for this, I had a blast playing with the css
