### ISSUE TITLE
Dev environment not functional

### ISSUE THREAD

**Issue by punfil** [koillection/koillection#821]
Hi,
I've observed that a month ago there was a commit: https://github.com/benjaminjonard/koillection/commit/b656f8f8a9a1408dd6cd818b625e3d3773e67de8 introduced that changed dev space docker config:
```bash
build:
            dockerfile: Dockerfile.dev
```
to
```bash
image: koillection/koillection
```
This removed all dev tools from dev environment (e.g. yarn). I would like to understand better why it was done and how one should proceed with development from now on.

Locally, I reverted this commit (on top of 1.4), but app doesn't work for me:

![obraz](https://github.com/benjaminjonard/koillection/assets/77413489/2d9cc48c-fa84-40aa-b053-85b996b5dea1)

I use mysql as DB driver.
During build I encountered some problems as well, but was able to WA them:
```bash
root@d1e2aa09fe82:/var/www/koillection/assets# yarn build
yarn run v1.22.19
$ encore production --progress
/bin/sh: 1: encore: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
then:
```bash
root@d1e2aa09fe82:/var/www/koillection/assets# yarn add symfony/webpack-encore
```
and build works:
```bash
root@d1e2aa09fe82:/var/www/koillection/assets# yarn build
yarn run v1.22.19
$ encore production --progress
Running webpack ...

99% done plugins FriendlyErrorsWebpackPlugin DONE  Compiled successfully in 55285ms                                                                                                                                                          5:57:47 PM

57 files written to /var/www/koillection/public/build
Entrypoint app [big] 644 KiB = runtime.69ecc27f.js 4.04 KiB 594.9a578ad2.css 119 KiB 594.a842843f.js 362 KiB app.3fa0a263.css 45 KiB app.b496f3a7.js 113 KiB
Entrypoint export 4.11 KiB = runtime.69ecc27f.js 4.04 KiB export.01d59534.css 72 bytes
Entrypoint dark 6.8 KiB = runtime.69ecc27f.js 4.04 KiB dark.91d6b55b.css 2.76 KiB
Entrypoint light 6.3 KiB = runtime.69ecc27f.js 4.04 KiB light.fbf9181b.css 2.26 KiB
webpack compiled successfully
Done in 57.32s.
root@d1e2aa09fe82:/var/www/koillection/assets# 
```
I am suprised, because symfony/webpack-encore-bundle is present in composer.json.

I would like to ask for help debugging issue I encountered. Last known working version for me is: a5afcb6a96b3ab95ce755d7c82d964a6ebca25d5.

I've tried my best to commit some changes:
https://github.com/benjaminjonard/koillection/pull/822

Greetings,
Wojciech

**Comment by benjaminjonard** [comment]
Hi,  

You are right, I made a lot of changes around Docker images and forgot to properly update the docker-compose file.
Your PR is good, we should also change these settings to have a fully working dev environment : 

- APP_DEBUG=1
- APP_ENV=dev
- HTTPS_ENABLED=0

As for the webpack library I'm going to have a closer look, Symfony made some changes recently on how it handles webpack.

Thanks !

**Comment by punfil** [comment]
Thanks for your quick reply.

I think the PR should be ready from my side. I am delighted to be able to contribute to your project.

Greetings,
Wojciech

**Comment by benjaminjonard** [comment]
I merged the PR. I'll close the issue once i've investigated the webpack issue.

Thanks again !

**Comment by punfil** [comment]
Recently, issue disappeared. Everything seems to be working now. I learned that I yarn init is required and the issue with encore missing no longer applies then as well.
