### ISSUE TITLE
Request: Year picker for dates

### ISSUE THREAD

**Issue by leezer3** [koillection/koillection#825]
Would like a year picker for dates added :)

I'm trying to catalog some somewhat older stuff at the minute, and would like to use publication date as a field.
At the minute, the only sensible way to add dates many years in the past (1960s) is to manually tab into the field and edit it.

A marginally related bug:
Using an incorrect date format or separator after tabbing into a date field will cause a 500 error,

**Comment by benjaminjonard** [comment]
The datepicker from the front library Koillection uses has some bugs. For now I fixed the datepicker, the year is now properly clickable and a select is available with years between 1 to now + 10 years

I'll publish a new release in the next few days

**Comment by benjaminjonard** [comment]
The last release should make it a bit easier to select a year from the datepicker
