### ISSUE TITLE
[Feature Request] Item quantity in Collection items overview

### ISSUE THREAD

**Issue by Walter-o** [koillection/koillection#830]
Hey!

I usually own multiple of any given item and i was kind of confused that there isn't a quantity overview yet.

The attached image explains the feature i am suggesting:
![koillection feature example](https://github.com/benjaminjonard/koillection/assets/33218378/38fed1f7-eda4-4297-8d73-501d5d4111cf)

**Comment by AlfaJackal** [comment]
Should be also in the list view! Yes, I would love to see that.

**Comment by Walter-o** [comment]
Is this feature already in the works or implemented?

I can't check at the moment since i blew up all thumbnail data by accident and i still have to clean up the mess.

If it's not implemented yet then i might try to do some docker-compose volume mod as a hack to get it to work (i will share it here if i manage to do it)

**Comment by benjaminjonard** [comment]
Hi, I will work on this for the next release

**Comment by Walter-o** [comment]
Appears to be working!
In both grid and list view
![image](https://github.com/benjaminjonard/koillection/assets/33218378/0ce18254-85ec-479f-b5f1-31071afa3df6)
![image](https://github.com/benjaminjonard/koillection/assets/33218378/6710472c-dc2e-4042-ba5b-593816522300)
