### ISSUE TITLE
[DOS Bug] Full application hang due to wishlist action

### ISSUE THREAD

**Issue by Walter-o** [koillection/koillection#831]
### **The bug**
Assigning 2 wishlists as parents of each other causes instant destruction of the universe

### **How to replicate**
- Make 2 wishlists
- Make sure wishlist 1 is parent of wishlist 2
- Go to the Edit page of wishlist 2
- Set it's parent to wishlist 1

### **The aftermath**
![image](https://github.com/benjaminjonard/koillection/assets/33218378/81463688-da5e-4b90-ad30-615db6943d1e)
The application hangs indefinitely and trying to load the page results in a 504 Gateway Time-out

After manually restarting the app, everything appears to be back to normal (So the database call probably didn't commit).

**Comment by benjaminjonard** [comment]
Thanks for reporting this, it will be fixed in the next release
