### ISSUE TITLE
Importer Ancienne base de données / Import Old database.

### ISSUE THREAD

**Issue by Raijin-MK** [koillection/koillection#839]
Bonjour/Bonsoir,

Mon ancien NAS à crashé, j'ai pu récupérer une backup à temps.
J'utilise docker.
Est-il possible de réinjecté le SQL et les images dans la nouvelle instance ?
Je n'ai rien trouvé sur le wiki, pouvez-vous m'aiguiller ?

En vous remerciant par avance.

--------------

Hello/Good evening,

My old NAS crashed, I was able to recover a backup in time.
I use Docker.
Is it possible to reinject the SQL and images into the new instance? 
I haven't found anything on the wiki, can you point me in the right direction?

Thank you in advance.

**Comment by benjaminjonard** [comment]
Hello, 

How did you make that backup ? (did you use a backup software or did you download the SQL and images from the Koillection admin interface ?)

If you backed up directly the docker volumes, you should just be able to copy those volumes and the docker-compose file and you should be good to go.

**Comment by Raijin-MK** [comment]
I downloaded the SQL and Images from Koillection admin interface.

**Comment by benjaminjonard** [comment]
Ok, then first thing you need to do is import the SQL to a brand new database. You could use phpmyadmin or pgadmin if you want a GUI to make the import. 

I would do this by commenting all containers but the database from the docker-compose.yml and start up the container. This should create a brand new instance of Mysql or Postgresql. Using the GUI you'd need to create a new database called koillection (with `utf8mb4_unicode_ci` if using Myqsl) and then execute the SQL file.

For images, when decompressing the archive you should have 1 folder per user identified by the user id. Just move those folders into your docker volume for uploads.

So if your volume is configured like this : 
     - ./volumes/koillection/uploads:/uploads
 Put them into ./volumes/koillection/uploads

That should do the trick, hope it can help you. I'm not home right now but if you are stuck I'll try to help

**Comment by Raijin-MK** [comment]
Bonjour,

Désolé pour la réponse extrêmement tardive.

Après installation et connexion à la base de données, au moment de faire la restauration en utilisant le fichier sql télécharger via l'interface d'administration.
PGAdmin 4 me donne l'erreur suite : "pg_restore: error: input file does not appear to be a valid archive".
Je n'arrive pas à restaurer ma base de données.

En attente de votre réponse,
Cordialement.

**Comment by Raijin-MK** [comment]
Bonjour,

Malgré plusieurs tentatives rien ne fonctionne, je me vois donc dans l'obligation de tout refaire manuellement.

Je ne sais pas si c'est possible mais une fonctionnalité d'import/export pourrais être utile.

Bonne continuation.
