### ISSUE TITLE
[BUG] Translation template modal Delete

### ISSUE THREAD

**Issue by brunoccr** [koillection/koillection#902]
Please put the delete modal buttons using the translation framework.

"templates\App\_partials\_modal\_delete.html.twig"

![image](https://github.com/benjaminjonard/koillection/assets/5890352/ba723c2b-9457-4026-a4bd-4521dcd36a4f)

**Comment by benjaminjonard** [comment]
Done, I added both to the translation files (I updated the wording a bit too)
