### ISSUE TITLE
[Improvement] New field type: Enum

### ISSUE THREAD

**Issue by Matthieu-LAURENT39** [koillection/koillection#912]
A field type that i feel would be very useful is a Enum/dropdown datatype, where you can set predefined values, and the user must pick between one of them.
While this is already *technically* possible using the `Text` field type, it lacks the convenience that a dropdown menu with predefined values would bring. You also risk accidentally writing slightly different text.

**Comment by benjaminjonard** [comment]
If I understand correctly, I believe the 'Choice List' menu will allow you to do exactly that. In this menu, you can create dropdown lists with custom entries and use them when adding an item.

**Comment by Matthieu-LAURENT39** [comment]
That indeed sounds exactly like what i need, but it doesn't show up when i'm trying to add a field.
Is that a planned feature?

**Comment by benjaminjonard** [comment]
Once you've created your custom choice list from the left menu, it should appear as a selectable field, at the buttom


![Screenshot 2023-09-04 at 15-10-19 Koillection](https://github.com/benjaminjonard/koillection/assets/20560781/3f09b31e-96d9-4082-95a1-ae7c06168a9f)

**Comment by Matthieu-LAURENT39** [comment]
Ahhh, i see, thanks!
