### ISSUE TITLE
Error when setting default template for collection

### ISSUE THREAD

**Issue by JSa1987** [koillection/koillection#927]
Hello,

This project seems very interesting and I wanted to give it a try.
After some initial troubles getting it setup I finally managed to get Koillection running in docker under Debian 11 via Portainer.
For some reason I could not get it to run with postgres, but I could set it up with mysql.

Now that Koillection is running I have to say this is exactly what I was looking for. However, I'm having some issues using templates.
I have created a template and if I pick this template when creating a new item everything works as expected. However, if select this same template when creating a new collection ("Apply a template" option) the new collection is created but is unaccessible (when I try to open it I get a "Oops, a critical error occurred :( " page). Same thing happens if I first create a new collection (that I can access) and then I edit it to add the template.

I would like to post the logs, but I cannot find the log file. The FAQ mentions that the log file should be /var/logs/prod.log, however I do not have the /var/logs/ directory. I have a /var/log/ directory with the following content (no prod.log file):
```
root@HO-koillection:/var/log# ls
alternatives.log  bootstrap.log  dpkg.log  journal  nginx           private
apt               btmp           faillog   lastlog  php8.2-fpm.log  wtmp
root@HO-koillection:/var/log# 
```

**Comment by benjaminjonard** [comment]
Hello
I couldn't reproduce, would you mind sharing the content of your template ?

For the logs they should be in ./var/logs at the root of the project

**Comment by JSa1987** [comment]
Hello @benjaminjonard ,

Thank you for the prompt follow up on this.

Below is the template I'm trying to use:
![image](https://github.com/benjaminjonard/koillection/assets/62815008/2b2ba298-b0bf-499a-ada4-6adea55d0b83)

As mentions this works fine if I pick this template when I create a new item. However, if I select this same template when I create a collection or edit a collection ("Apply a template" option) I then cannot open anymore said collection, I get a "Oops, a critical error occurred :( " page)."

When this happens (i.e. when I try to open a collection that has this template set as Apply a template" option) the following is recorded in the log:

`{"message":"Uncaught PHP Exception TypeError: \"App\\Twig\\IntlExtension::App\\Twig\\{closure}(): Argument #1 ($code) must be of type string, null given, called in /var/www/koillection/var/cache/prod/twig/d7/d7aec3803f7b4b26cbc22b512b816332.php on line 37\" at /var/www/koillection/src/Twig/IntlExtension.php line 18","context":{"exception":{"class":"TypeError","message":"App\\Twig\\IntlExtension::App\\Twig\\{closure}(): Argument #1 ($code) must be of type string, null given, called in /var/www/koillection/var/cache/prod/twig/d7/d7aec3803f7b4b26cbc22b512b816332.php on line 37","code":0,"file":"/var/www/koillection/src/Twig/IntlExtension.php:18"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2023-09-17T21:05:09.323865-05:00","extra":{}}`

**Comment by houdini69** [comment]
I got the same issue when setting a default template and creating a new item. In the log

`{"message":"Uncaught PHP Exception TypeError: \"App\\Twig\\IntlExtension::App\\Twig\\{closure}(): Argument #1 ($code) must be of type string, null given, called in /var/www/koillection/var/cache/prod/twig/3b/3ba9db6d882c661fe0043c60f23326a3.php on line 40\" at /var/www/koillection/src/Twig/IntlExtension.php line 18","context":{"exception":{"class":"TypeError","message":"App\\Twig\\IntlExtension::App\\Twig\\{closure}(): Argument #1 ($code) must be of type string, null given, called in /var/www/koillection/var/cache/prod/twig/3b/3ba9db6d882c661fe0043c60f23326a3.php on line 40","code":0,"file":"/var/www/koillection/src/Twig/IntlExtension.php:18"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2023-09-18T17:19:41.493422+00:00","extra":{}}
`

**Comment by houdini69** [comment]
And

`in[ src/Twig/IntlExtension.php ](file:///var/www/koillection/src/Twig/IntlExtension.php#L18)(line 18)

        {
            return [
                new TwigFunction('getCountriesList', static function (): array {
                    return (new IntlRuntime())->getCountriesList();
                }),
                new TwigFunction('getCountryName', static function (string $code): string {
                    return (new IntlRuntime())->getCountryName($code);
                }),
                new TwigFunction('getCountryFlag', static function (string $code): string {
                    return (new IntlRuntime())->getCountryFlag($code);
                }),`

**Comment by houdini69** [comment]
After several attempts when I set "Country label" there is no issue!

**Comment by JSa1987** [comment]
> After several attempts when I set "Country label" there is no issue!

Hello @houdini69 could you please clarify where you set the "Country label" to fix this?

**Comment by JSa1987** [comment]
Ok, after reading again the comment from @houdini69 a couple of times and trying several things I think I understood how to reproduce this and how to avoid the issue.

First of all let me start by saying that I had miss understood he functionality of selecting a template when creating a collection. In my mind selecting a template when creating a collection was intended to force all the items withing that collection to use that template by default. And therefore when I was creating a new collection I was selecting the template but not populating any of the values.

If a template that has a country type attribute is selected for a collection (either when creating or when editing the collection) and no value (country) is selected this the issue will manifest itself (i.e. the collection won't be accessible anymore).

I have however realized that the selecting a template when creating (or editing) a collection is not intended to force all the items in that collection to use that template, but just to define attributes for the collection itself. As such it does not make much sense to add a country type attribute without populating it.
However, it might still be good to fix this to prevent a collection for becoming unaccessible in case somebody by mistake adds a country type attribute without selecting value.

**Comment by JSa1987** [comment]
Just to complete this I had confused the "Apply a template" option of a collection with the "Default template applied to items" option.

**Comment by benjaminjonard** [comment]
I found the issue, I'll publish a new release with the fix probably tomorrow
