### ISSUE TITLE
Updating Koillection impossible

### ISSUE THREAD

**Issue by houdini69** [koillection/koillection#935]
Hi,
After the new update 1.4.12 I tried to update according to the wiki but this third command gives that,

sudo php bin/console bazinga:js-translation:dump assets/js --format=js
There are no commands defined in the "bazinga:js-translation" namespace.  
                                                                            
  Did you mean this?                                                        
      app:translations

**Comment by benjaminjonard** [comment]
Hello

Yes the new command is  `app:translations:dump`, I will update the wiki

**Comment by houdini69** [comment]
Thanks `sudo php bin/console app:translations:dump` command works!

However when I connect again to my koillection instance it's stil the previous version 1.4.11.

**Comment by houdini69** [comment]
As I was unable to update with commands from wiki I installed successfully Koillection 1.4.12 from scratch.
