### ISSUE TITLE
HTTP request failed! HTTP/1.1 403 Forbidden

### ISSUE THREAD

**Issue by houdini69** [koillection/koillection#952]
Got this warning when trying to scrap vinyl on discogs,

Warning: file_get_contents(https://www.discogs.com/service/header/public/assets/assets/logo-83221bf3.svg): Failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden

Is it an issue with discogs or my instance? Scrapping was working previously.

**Comment by benjaminjonard** [comment]
Seems like discogs made a few changes in their HTML. If you are using the scraper provided as an example, it should work if you change the image path from `#(//img)[1]/@src#`  to `#(//img)[2]/@src#`

**Comment by houdini69** [comment]
Thanks! Changing image path as suggested fixes this issue.

**Comment by houdini69** [comment]
It looks like there have been some changes on Discogs again. 

I got a 403 error when trying the Discogs script provided in the wiki.

`
HTTP/2 403 returned for "https://www.discogs.com/fr/artist/162564-Astor-Piazzolla".
`
