### ISSUE TITLE
Error 500 after item adding 

### ISSUE THREAD

**Issue by max2k** [koillection/koillection#967]
There is a strange issue with adding item to collection. After 50 items it is possible to add only items without picture, if item added with one title picture there is 500 error, no matter adding new item or change it by edit option. Docker image created 2023-09-20 15:54:25 access log messages:

192.168.12.1 - - [07/Nov/2023:11:08:18 +0000] "GET /items/b7ca5519-1f7c-4844-8c58-cbb8fcfcdfd5/edit HTTP/1.1" 200 12502 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
192.168.12.1 - - [07/Nov/2023:11:08:25 +0000] "POST /items/b7ca5519-1f7c-4844-8c58-cbb8fcfcdfd5/edit HTTP/1.1" 500 1027 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"

**Comment by benjaminjonard** [comment]
That's weird there is no limitation on item number. Could you add this environment variable to your docker-compose.yml ?  It should give more informations about this error

APP_DEBUG=1

**Comment by retrogamer1337** [comment]
I have a similar problem. When I try to upload an image it tells me `The server returned a "500 Internal Server Error".`

Using the latest container version on Unraid. Was uploading images with no problems and from one minute to the other I got the 500 error.

APP_DEBUG=1 has in impact for me, I see no logs when I check the logs for the docker in unraid or anything that could help.

**I managed to upload a 2kB image with no issues.** But when I try a 10kB Image or even bigger the 500 error appears.

**Comment by max2k** [comment]
It is a limit for uploading images. Check your account preferences.

**Comment by retrogamer1337** [comment]
indeed

**511.98 MiB of 512 were used. Changed it to 5GiB now.** 

Thank YOU!

**Comment by benjaminjonard** [comment]
I have fixed this process for the next release. The error will now be properly displayed on the form instead of throwing a generic error.
