### ISSUE TITLE
"Migration can only be executed safely on postgresql" attempt updating koillection to 1.4.13

### ISSUE THREAD

**Issue by houdini69** [koillection/koillection#973]
Tried to update to version 1.4.13.
1. sudo composer install --classmap-authoritative
-> Ok
2. sudo php bin/console doctrine:migrations:migrate
....
[notice] Migration App\Migrations\Postgresql\Version20230803152739 skipped during Execution. Reason: "Migration can only be executed safely on 'postgresql'."

4. sudo php bin/console app:translations:dump
-> Ok

After logging to koillection displayed version on Administration page is still 1.4.12
Instead of postgresql I switched to mysql so how to update in this case?

**Comment by benjaminjonard** [comment]
The version number from the admin panel is unrelated to the the database. It only comes from the config/services.yml file.
I only see two explanations for this problem, either the code isn't up to date, or there is a cache problem. Try removing the var/cache folder and restarting php-fpm (it will clear the php opcache)

**Comment by houdini69** [comment]
Restarting php-fpm did nothing. What file should I remove in /var/cache?

**Comment by benjaminjonard** [comment]
You can remove all of them, they will be regenerated

**Comment by houdini69** [comment]
Removing cache files did nothing.

**Comment by houdini69** [comment]
As I couldn't update as stated in the wiki. Is it possible to install the new version and just replace .env configuration file and uploads folder?

**Comment by benjaminjonard** [comment]
Yes, it will work as long as you execute the commands from the wiki after making the .env replacement.

I think I understand the problem now, I'll update the wiki

**Comment by houdini69** [comment]
Update to version 1.4.13 was successful.
Thanks!
