### ISSUE TITLE
[Bug] Small image is deleted when transfering a wishlist item to a collection

### ISSUE THREAD

**Issue by Matthieu-LAURENT39** [koillection/koillection#985]
# Issue
When transfering a wishlist item to collection, the small image (the thumbnails in the collection) will be deleted.
The full sized image is properly kept.

# Steps to reproduce
1. Create a wishlist item, with a cover image
2. Transfer that wishlist item to a collection.
3. The image will probably still be shown. Force a refresh with shift+F5. The image will now be gone.
In fact, it's even worse than gone, the image tries to load, but won't. This makes it really hard to click as there is just a tiny "image loading failed" icon.

# Example
![image](https://github.com/benjaminjonard/koillection/assets/91389613/0bb469a3-4609-4fe1-b56d-45936b536bf5)

# Version
Issue happens on the latest version (`1.4.13`)

**Comment by Matthieu-LAURENT39** [comment]
And just in case it matters, the "thumbnail format" in settings is "Keep original"

**Comment by benjaminjonard** [comment]
Thanks, the issue will be fixed in the next release

**Comment by Matthieu-LAURENT39** [comment]
Closing as this is fixed (tested on v1.5.3)
